name: uni_links
description: Flutter plugin for accepting incoming links - App/Deep Links (Android), Universal Links and Custom URL schemes (iOS).
version: 0.5.1
homepage: https://github.com/avioli/uni_links/tree/master/uni_links
publish_to: none

dependencies:
  flutter:
    sdk: flutter
  uni_links_platform_interface:
    path: ../uni_links_platform_interface
  uni_links_web:
    path: ../uni_links_web

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=3.12.2 <4.0.0"
  flutter: ">=3.44.7"

flutter:
  plugin:
    platforms:
      android:
        package: name.avioli.unilinks
        pluginClass: UniLinksPlugin
      ios:
        pluginClass: UniLinksPlugin
      web:
        default_package: uni_links_web
